--- 
- 
  hosts: all
  name: "welcome to playbook"
  tasks: 
    - 
      name: "service installation"
      yum: "name=httpd state=latest"
    - 
      name: "start service"
      service: "name=httpd state=started"
