---
- name: Lab 2
  hosts: ARS
  tasks:
    - name: create a group called “deploy”
      group:
        name: deploy
        state: present
    - name: create user deploy and add to group
      user:
        name=deploy-user
        group=deploy
        shell=/bin/bash
    - name: install package httpd
      yum:
        name=httpd
        state=installed
    - name: start httpd service and enabled
      service:
        name=httpd
        state=started
        enabled=yes
    - name: create file in root directory httpd
      copy:
        src=index.html
        dest=/var/www/html
    - name: reboot the machine
      reboot:
        reboot_timeout=3600
    - name: install packages git
      yum:
        name=git state=installed
    - name: install packages wget
      yum:
        name=wget state=installed
    - name: clone repository
      git:
        repo=https://github.com/scmgalaxy/ansible-role-template.git
        dest=/opt/ansible-role-template
